################################################################################
#                              k8s-install_kube.yml                            #
#------------------------------------------------------------------------------#
# Date        Name      Version Description                                    #
# 2023/09/07  Jander    01.00   Install kubeadm, kubectl, kubelet CRI          #
################################################################################
---
- name: Install kube
  hosts: masters,workers
  remote_user: ti
  become: yes
  become_method: su
  become_user: root
  gather_facts: yes
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - sudo
          - nfs-kernel-server
        state: latest


    # Disable swap------------------------------------------------------------------
    - name: disable swap
      shell: |
              sudo swapoff -a
              sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    # Modules ---------------------------------------------------------------------
    - name: Create k8s containerd config file
      ansible.builtin.file:
        path: /etc/modules-load.d/k8s.conf
        state: touch

    - name: Add conf for k8s.conf
      blockinfile:
        path: /etc/modules-load.d/k8s.conf
        block: |
              overlay
              br_netfilter

    - name: modprobe
      community.general.modprobe:
        name: overlay
        state: present

    - name: modprobe
      community.general.modprobe:
        name: br_netfilter
        state: present

    - name: Set system configurations for Kubernetes networking
      ansible.builtin.file:
        path: /etc/sysctl.d/k8s.conf
        state: touch

    - name: Add conf for containerd
      blockinfile:
        path: "/etc/sysctl.d/k8s.conf"
        block: |
              net.bridge.bridge-nf-call-iptables = 1
              net.ipv4.ip_forward = 1
              net.bridge.bridge-nf-call-ip6tables = 1

    - name: Apply new settings
      command: "/usr/sbin/sysctl --system"

    # Docker --------------------------------------------------------------------
    - name: Install packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg 
        state: latest
        update_cache: true

    - name: Add key repo docker  
      ansible.builtin.apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        keyring: /etc/apt/keyrings/docker.gpg
      
    - name: Add repo Docker
      apt_repository:
        filename: docker_repo
        repo: deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ansible_distribution_release}} stable
        mode: 0644
        state: present

    - name: install CRI Docker
      apt:
        pkg:
          - containerd
#          - containerd.io
#          - docker-ce
#          - docker-ce-cli
#          - docker-buildx-plugin
#          - docker-compose-plugin
#        state: latest
#        update_cache: true

#    - name: Start docker service
#      ansible.builtin.service:
#        name: docker.service
#        state: started
#        enabled: true 
      
    # CGroupDriver ------------------------------------------------------------------
    - name: Configure CGroup Driver
      shell: |
              sudo mkdir -p /etc/containerd
              sudo containerd config default | sudo tee /etc/containerd/config.toml
              sed -e 's/SystemdCgroup = false/SystemdCgroup = true/g' -i /etc/containerd/config.toml

    - name: Restart containerd service
      ansible.builtin.service:
        name: containerd.service
        state: restarted
        enabled: true 


    # Kubeadm, kubelet e kubectl ----------------------------------------------------
    - name: Add an Apt signing key to a specific keyring file
      ansible.builtin.apt_key:
        id: A362B822F6DEDC652817EA46B53DC80D13EDEF05
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg
 
    - name: Add repo Kubernetes
      apt_repository:
        filename: kubernetes_repo
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        mode: 0644
        state: present

    - name: install kubeadm, kubelet, kubectl
      apt:
        pkg:
          - kubelet
          - kubeadm
          - kubectl
        state: latest
        update_cache: true

    - name: Restart containerd service
      ansible.builtin.service:
        name: kubelet.service
        state: started
        enabled: true
