################################################################################
#                              k8s-join_worker.yml                             #
#------------------------------------------------------------------------------#
# Date        Name      Version Description                                    #
# 2023/09/07  Jander    01.00   Join Node Worker on k8s Cluster                #
################################################################################
---

- name: Join node workers
  hosts: masters
  remote_user: user
  become: yes
  become_method: su
  become_user: root
  gather_facts: yes
  tasks:
  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact: join_command_k8s="{{ join_command_raw.stdout }}"


- name: join cluster
  hosts: workers
  remote_user: user
  become: yes
  become_method: su
  become_user: root
  gather_facts: no
  tasks:
  - name: Limpar kubeadm
    ansible.builtin.command: kubeadm reset -f
      
  - name: debug
    ansible.builtin.debug:
      msg: "{{ hostvars[groups['masters'][0]]['join_command_k8s'] }}"
    
  - name: Join worker
    ansible.builtin.command: "sudo {{ hostvars[groups['masters'][0]]['join_command_k8s'] }}" 

